<a href="https://colab.research.google.com/github/asheta66/CNN-WorkOut/blob/main/Lesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is NumPy?**

•	NumPy is a Python library used for working with arrays.

•	It also has functions for working in domain of linear algebra, fourier transform, and matrices.

•	NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

•	NumPy stands for Numerical Python.



In [2]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

for x in arr:
  print(x)

print(arr[1:5])
print('shape of array :', arr.shape)

1
2
3
4
5
[2 3 4 5]
shape of array : (5,)


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)
print('shape of array :', newarr.shape)
print(newarr)

shape of array : (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [25]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]
